//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateRoomDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveRooms
    {
        public int RoomId { get; set; }
    
        public virtual PrivateRooms PrivateRooms { get; set; }
    }
}
