//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateRoomDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.PrivateRooms = new HashSet<PrivateRooms>();
        }
    
        public int CourseId { get; set; }
        public string CourseAcronym { get; set; }
        public string CourseName { get; set; }
        public int SubscribedCount { get; set; }
        public int MaxSubscription { get; set; }
        public int TrimesterId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> CourseInfoId { get; set; }
        public Nullable<int> CourseInfoLabId { get; set; }
        public Nullable<int> GroupNumber { get; set; }
    
        public virtual CourseInfo CourseInfo { get; set; }
        public virtual CourseInfo CourseInfo1 { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Trimesters Trimesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateRooms> PrivateRooms { get; set; }
    }
}
