//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateRoomDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrivateRooms()
        {
            this.Courses = new HashSet<Courses>();
        }
    
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public string RoomPassword { get; set; }
        public string OwnerId { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual ActiveRooms ActiveRooms { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
