//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateRoomDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public int UserProfileId { get; set; }
        public int DepartmentId { get; set; }
        public int EnrollmentYear { get; set; }
        public int CreditsToDate { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
